name: "Build Drupal 8+ release"
description: 'Checkout a Drupal composer-base repository and create an artifact release'
inputs:
  phplint:
    description: 'Run PHP Lint'
    required: true
    default: 'true'
  phpmd:
    description: 'Run PHP Mess Detector'
    required: true
    default: 'true'
  phpcs:
    description: 'Run PHP Code Sniffer'
    required: true
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Check - PHP syntax
      if: ${{ inputs.phplint == 'true' }}
      run: ./vendor/bin/phplint --no-cache --no-progress --extensions=php,module,inc,install,test,theme ./web/themes/custom/ ./web/modules/custom/
      shell: bash

    - name: Check - PHP MD on modules
      if: ${{ inputs.phpmd == 'true' }}
      run: ./vendor/bin/phpmd  ./web/modules/custom/ xml phpmd.xml
      shell: bash

    - name: Check - PHP Code Sniffer
      if: ${{ inputs.phpcs == 'true' }}
      run: ./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,profile,theme,test,css,info,txt,md,yml ./web/modules/custom/ ./web/themes/custom/
      shell: bash
